[package]
name = "proc-quote-impl"
version = "0.1.0"
authors = ["PedroGonçaloCorreia <goncalerta@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A procedural macro implementation of quote!."
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = { version = "0.6.11" }
proc-macro-hack = "0.5.4"
proc-macro2 = { version = "0.4.26", default-features = false }